### ISSUE TITLE
UMA NOVA TELA DE RELATÓRIO ANUAL

### ISSUE THREAD

**Issue by Zeteago** [Zeteago/barbearia#7]
- RELATORIO DO ANO ATUAL ATÉ O PRESENTE MOMENTO
- RELATORIO DO ANO ANTERIOR
- RELATORIO DO MÊS ATUAL ATÉ O PRESENTE MOMENTO
- RELATORIO DOS MESES ANTERIORES (DESDE JANEIRO) APÓS ISTO O RELATÓRIO GUARDADO SERÁ O ANUAL (MOSTRANDO O TOTAL MAS TAMBÉM CADA MÊS)
![imagem_2024-12-11_202432249](https://github.com/user-attachments/assets/e595da96-17a6-40d9-b33a-c40541fd45cc)

**Comment by FioriMartins** [comment]
Estou adorando observar a construção projeto!
